# Utiliser une image Node.js
FROM node:22-slim

# Définir le répertoire de travail dans le conteneur
WORKDIR /app

# Installer les dépendances
COPY package*.json ./
RUN npm install

# Exposer le port sur lequel le serveur de développement fonctionne
EXPOSE 8080

# Commande par défaut (assurez-vous que "start" est défini pour le mode dev dans package.json)
CMD ["npm", "run", "serve:dev"]