# Utiliser une image Node.js
FROM node:22-slim

# Install OpenSSL and other required dependencies
RUN apt-get update -y && apt-get install -y openssl

# Définir le dossier de travail
WORKDIR /app

# Copier les fichiers nécessaires avant d'installer les dépendances
COPY package.json package-lock.json ./
COPY backend/package.json backend/package-lock.json ./backend/
COPY backend/tsconfig.json ./backend/
COPY backend/prisma ./backend/prisma
COPY backend/src ./backend/src /
COPY backend/tests ./backend/tests

# Forcer NODE_ENV à "development" pour inclure les devDependencies
ENV NODE_ENV=development

# Installer TOUT le monorepo, mais on ne build que le workspace "back"
RUN npm ci

# Aller dans le dossier back et build
WORKDIR /app/backend
RUN npm ci
RUN npx prisma generate
RUN npm run build

EXPOSE 3000
CMD ["npm", "run", "start"]
