# Utiliser une image Node.js
FROM node:22-slim

# Install OpenSSL and other required dependencies
RUN apt-get update -y && apt-get install -y openssl

# Définir le dossier de travail
WORKDIR /app

# Copier les fichiers de configuration du monorepo
COPY package.json package-lock.json ./

# Installer TOUT le monorepo, mais on ne build que le workspace "back"
RUN npm ci

# Aller dans le dossier back et build
WORKDIR /app/backend

# Copie le fichier de configuration du backend
COPY backend/package.json backend/package-lock.json ./

# Installe les dépendances
RUN npm ci
EXPOSE 3000

CMD ["npm", "run", "start"]
