name: Lint, Test, Build, and Deploy

on: 
  push:
    branches:
      - main

jobs:
  lint-test-build-deploy:
    name: Lint with ESLint, Test with Jest, Build with Webpack, and Deploy for Front and Back
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      # FRONT-END WORKFLOW
      - name: Set up Node.js for Front-end
        uses: actions/setup-node@v3
        with:
          node-version: '22.9.0'

      - name: Install dependencies for root folder
        run: |
          npm install

      - name: Install dependencies for Front-end
        run: |
          cd frontend
          npm install

      - name: Run ESLint without autofix
        run: |
          cd frontend
          npx eslint .

      - name: Run Jest tests
        run: |
          cd frontend
          npm test

      - name: Build with Webpack
        run: |
          cd frontend
          mkdir -p dist
          npm run build:prod
      
      # - name: Move HTML and CSS files to dist
      #   run: |
      #     cd frontend
      #     mkdir -p dist
      #     mv src/*.html dist/
      #     mv src/*.css dist/

      - name: Sync assets folder to dist using rsync
        run: |
          cd frontend
          mkdir -p dist/assets
          rsync -av src/assets/ dist/assets/

      # ADD BACK-END WORKFLOW

      # ADAPT DEPLOY TO GOOGLE CLOUD RUN

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend/dist