name: Lint and Test

on: 
  push:
    branches:
      - main

jobs:
  lint-test-build-deploy:
    name: Lint with ESlint, Test with Jest, Build with Webpack, and Deploy with GitHub Pages
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.9.0'

      - name: Install dependencies
        run: npm install

      - name: Run ESLint without autofix
        run: npx eslint@8.0.1 .
      
      - name: Run Jest tests
        run: npm test

      - name: Build with Webpack
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist